os: linux
dist: bionic
language: cpp

branches:
  only:
  - master
  - dev

addons:
  apt:
    update: true
    packages:
      - cmake
      - libboost-all-dev
      - python3-pip
      - linux-tools-5.0.0-1031-gcp

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Release

before_script:
  - git lfs pull
  - git submodule init
  - git submodule update
  - bash download_models.sh
  - wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.5.0%2Bcpu.zip
  - unzip libtorch-cxx11-abi-shared-with-deps-1.5.0+cpu.zip
  - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx
  - wget https://www.dropbox.com/s/k31nutuzrtp2d9v/docs_20191209.tar.gz
  - tar -xzvf docs_20191209.tar.gz
  - python3 -m pip install -r json2html/requirements.txt
  - git clone https://github.com/brendangregg/FlameGraph
  - export LD_LIBRARY_PATH=$(if [[ $TRAVIS_COMPILER == "clang" ]]; then echo -n /usr/local/clang/lib:$LD_LIBRARY_PATH; fi)

script:
  - mkdir build
  - cd build
  - Torch_DIR="../libtorch" cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make -j2
  - make test
  - cd ..
  - bash test_canonical.sh
  - perf record -F 99 -g ./build/tgnews top docs_20191209.json --from_json > top_20191209.json
  - perf script > out.perf
  - python3 json2html/convert.py --documents-file docs_20191209.json --tops-file top_20191209.json --templates-dir json2html/templates --output-dir output
  - ./FlameGraph/stackcollapse-perf.pl out.perf | ./FlameGraph/flamegraph.pl > output/flamegraph.svg

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_GITHUB_TOKEN
  keep_history: false
  local_dir: output
  verbose: true
  on:
    branch: master
    condition: $TRAVIS_COMPILER = clang
